In [7]:
import numpy as np

In [2]:
np.intersect1d
np.setdiff1d

<function numpy.setdiff1d(ar1, ar2, assume_unique=False)>

In [3]:
arr_zeros=np.zeros(10,dtype=int)
arr_zeros[4]=1
print(arr_zeros)

[0 0 0 0 1 0 0 0 0 0]


In [5]:
arr_h=np.arange(10,25)
print(arr_h[::-1])

[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [9]:
arr_k=np.array([1,2,0,8,2,0,1,3,0,5,0])
arr_l=np.array([i for i in arr_k if i!=0])
print(arr_l)

[1 2 8 2 1 3 5]
